
import { Article } from './types';

export const INITIAL_ARTICLES: Article[] = [
  {
    id: '1',
    title: 'Indonesia Emas 2026: Proyeksi Pertumbuhan Ekonomi Melampaui 7%',
    excerpt: 'Langkah strategis hilirisasi digital dan energi terbarukan mulai menunjukkan hasil signifikan bagi devisa negara.',
    body: 'Memasuki pertengahan 2026, pemerintah mengumumkan bahwa pertumbuhan ekonomi Indonesia telah melampaui angka psikologis 7%. Menteri Koordinator Perekonomian menyatakan bahwa investasi besar-besaran di sektor semikonduktor lokal dan infrastruktur IKN tahap ketiga menjadi motor utama. Penguatan rupiah stabil di angka yang kompetitif, sementara ekspor kendaraan listrik buatan Indonesia mulai mendominasi pasar Asia Tenggara.',
    category: 'Ekonomi',
    author: 'Andi Pratama',
    publishedAt: '2026-05-15T10:30:00Z',
    imageUrl: 'https://picsum.photos/seed/econ2026/800/600',
    trending: true,
  },
  {
    id: '2',
    title: 'Timnas Indonesia Lolos Babak 16 Besar Piala Dunia 2026',
    excerpt: 'Sejarah tercipta di Amerika Utara setelah Skuad Garuda menaklukkan tim papan atas Eropa.',
    body: 'Gempita menyelimuti tanah air setelah Tim Nasional Indonesia dipastikan mengamankan tiket ke babak 16 besar Piala Dunia 2026. Kemenangan dramatis 2-1 di menit-menit akhir pertandingan grup penutup menjadi kunci. Pelatih menyatakan bahwa disiplin taktik dan mentalitas "Kilat" pemain menjadi pembeda. Ini adalah pencapaian tertinggi sepak bola Indonesia sepanjang masa.',
    category: 'Olahraga',
    author: 'Budi Santoso',
    publishedAt: '2026-06-20T14:45:00Z',
    imageUrl: 'https://picsum.photos/seed/sports2026/800/600',
    trending: true,
  },
  {
    id: '3',
    title: 'Quantum Jakarta: Peluncuran Komputer Kuantum Pertama di ASEAN',
    excerpt: 'Pusat riset teknologi di BSD City berhasil mengoperasikan prosesor kuantum 128-qubit buatan anak negeri.',
    body: 'Indonesia resmi masuk dalam jajaran elit pemilik teknologi kuantum global. Startup "Nusantara Quantum" bekerja sama dengan BRIN meluncurkan operasional perdana komputer kuantum di kawasan teknologi Tangerang. Teknologi ini diprediksi akan mempercepat penelitian obat-obatan dan enkripsi siber nasional hingga ribuan kali lipat dibandingkan superkomputer konvensional.',
    category: 'Teknologi',
    author: 'Citra Dewi',
    publishedAt: '2026-03-12T08:00:00Z',
    imageUrl: 'https://picsum.photos/seed/tech2026/800/600',
  },
  {
    id: '4',
    title: 'Pemilu 2026: Digital Voting Resmi Diuji Coba Secara Nasional',
    excerpt: 'KPU memperkenalkan sistem pemungutan suara berbasis blockchain untuk menjamin transparansi mutlak.',
    body: 'Langkah revolusioner diambil dalam persiapan pesta demokrasi 2026. Komisi Pemilihan Umum (KPU) mengumumkan penggunaan sistem voting digital berbasis blockchain untuk pertama kalinya. Sistem ini memungkinkan warga memberikan suara melalui aplikasi identitas digital yang terenkripsi. Pengamat politik menilai ini adalah akhir dari era kecurangan administratif di tempat pemungutan suara.',
    category: 'Politik',
    author: 'Dedi Kusuma',
    publishedAt: '2026-02-28T19:20:00Z',
    imageUrl: 'https://picsum.photos/seed/pol2026/800/600',
    trending: true,
  },
  {
    id: '5',
    title: 'Metaverse Borobudur: Wisata Digital Indonesia Jadi Tren Dunia',
    excerpt: 'Jutaan turis mancanegara menikmati pengalaman imersif Candi Borobudur melalui perangkat XR.',
    body: 'Kementerian Pariwisata melaporkan lonjakan pendapatan dari sektor pariwisata digital. Platform Metaverse Borobudur yang diluncurkan awal tahun 2026 telah menarik 10 juta pengunjung unik secara global. Pengguna dapat merasakan atmosfer spiritual candi di masa keemasan melalui teknologi Extended Reality (XR) yang didukung koneksi 6G nasional yang mulai merata.',
    category: 'Hiburan',
    author: 'Eka Putri',
    publishedAt: '2026-04-10T11:00:00Z',
    imageUrl: 'https://picsum.photos/seed/ent2026/800/600',
  },
  {
    id: '6',
    title: 'IKN Jadi Kota 6G Pertama di Dunia: Kecepatan Internet Tembus 1Tbps',
    excerpt: 'Ibu kota baru Indonesia resmi mengaktifkan jaringan 6G komersial pertama secara global.',
    body: 'Nusantara (IKN) kembali mencuri perhatian dunia. Hari ini, infrastruktur telekomunikasi IKN resmi beralih ke teknologi 6G. Dengan latensi yang hampir nol, kota ini kini menjadi pusat uji coba mobil otonom tingkat lanjut dan operasi medis jarak jauh yang sangat presisi.',
    category: 'Teknologi',
    author: 'Citra Dewi',
    publishedAt: '2026-07-05T09:00:00Z',
    imageUrl: 'https://picsum.photos/seed/6gikn/800/600',
  },
  {
    id: '7',
    title: 'Vaksin Generasi Baru Produksi Dalam Negeri Resmi Diekspor',
    excerpt: 'Bio Farma mulai mendistribusikan vaksin mRNA buatan Indonesia ke negara-negara Afrika.',
    body: 'Prestasi gemilang di sektor kesehatan. Vaksin generasi terbaru yang dikembangkan sepenuhnya oleh peneliti lokal kini mulai memenuhi permintaan global. Ini menandai kemandirian farmasi Indonesia di kancah internasional.',
    category: 'Kesehatan',
    author: 'Dr. Sarah',
    publishedAt: '2026-08-12T10:00:00Z',
    imageUrl: 'https://picsum.photos/seed/health2026/800/600',
  },
  {
    id: '8',
    title: 'Konferensi Perdamaian Jakarta 2026: Pakta Stabilitas Kawasan Ditandatangani',
    excerpt: 'Jakarta menjadi saksi sejarah kesepakatan damai antara kekuatan besar di kawasan Asia Pasifik.',
    body: 'Diplomasi Indonesia membuahkan hasil besar. Melalui Konferensi Perdamaian Jakarta, para pemimpin dunia sepakat untuk menjaga stabilitas jalur perdagangan maritim, memberikan kepastian ekonomi bagi seluruh kawasan.',
    category: 'Dunia',
    author: 'Dedi Kusuma',
    publishedAt: '2026-09-01T15:30:00Z',
    imageUrl: 'https://picsum.photos/seed/peace2026/800/600',
  }
];
